# Generated by Django 3.1 on 2022-03-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres', to='centres.commune', verbose_name='الجماعة'),
        ),
        migrations.AddField(
            model_name='centre',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='centre',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
