# Generated by Django 3.2.3 on 2022-07-31 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centres', '0002_auto_20220310_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisme', models.CharField(blank=True, choices=[('EN REG', 'Entraide Nationale Provinciale'), ('EN PROV', 'Entraide Nationale Provinciale'), ('ANAPEC REG', 'ANAPEC Regionale'), ('ANAPEC PROV', 'ANAPEC Provinciale'), ('ADS', 'ADS'), ('INDH', 'INDH')], max_length=300, verbose_name='Organisme')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='centres.province')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='centres.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
