# Generated by Django 3.2.3 on 2022-08-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centres', '0004_alter_membre_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='organisme',
            field=models.CharField(blank=True, choices=[('EN REG', 'Entraide Nationale Regionale'), ('EN PROV', 'Entraide Nationale Provinciale'), ('ANAPEC REG', 'ANAPEC Regionale'), ('ANAPEC PROV', 'ANAPEC Provinciale'), ('ADS', 'ADS'), ('INDH', 'INDH')], max_length=300, verbose_name='Organisme'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
