"""
Django settings for coaph project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from django.utils.translation import gettext_lazy as _
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '45d+(f8l(y00_cu&%v)%wi^$!)c18%vf72kthqhoo%htlxja^x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['agr.pythonanywhere.com', 'localhost', '127.0.0.1']

LOGOUT_REDIRECT_URL= '/'

# Admin Menu App Conf
#ADMIN_LOGO = 'logo.png'

ADMIN_STYLE = {
    'primary-color': '#2B3746',
    'secondary-color': '#354151',
    'tertiary-color': '#F2F9FC',
    'logo-width': '0px',
    'logo-height': '0px'
}

MENU_WEIGHT = {
    'Auth': 100
}

# Application definition

INSTALLED_APPS = [
    #'bootstrap_datepicker_plus',
    'admin_menu',
    'import_export',
    #'django_tabbed_changeform_admin',
    'grappelli',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'beneficiaires.apps.BeneficiairesConfig',
    'projets.apps.ProjetsConfig',
    #'denrees.apps.DenreesConfig',
    #'protheses.apps.ProthesesConfig',
    #'aides.apps.AidesConfig',
    #'auditif.apps.AuditifConfig',
    #'implant.apps.ImplantConfig',
    'centres.apps.CentresConfig',
    #'marches.apps.MarchesConfig',
    #'inventaire.apps.InventaireConfig',
    #'attestation.apps.AttestationConfig',
    #'assistance.apps.AssistanceConfig',
    'wkhtmltopdf',
    'frontend',
   #'prothese',
    'qr_code',
    'corsheaders',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'djadmin.middleware.DJMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'agr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates'),
                 os.path.join(BASE_DIR,'django_admin_listfilter_dropdown', 'templates'),
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db-test.sqlite3'),
    }
    #'default': {
    #    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #    'NAME': 'eldqreag',
    #    'USER': 'eldqreag',
    #    'PASSWORD': 'JxKYeOLyiDjRbstLYLthOGM_pCquS4BL',
    #    'HOST': 'tai.db.elephantsql.com',
    #    'PORT': '5432',
    #}
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/


TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGE_CODE='ar'

LOCALE_PATHS=(
    os.path.join(BASE_DIR, 'templates/admin/locale'),
    os.path.join(BASE_DIR, 'django/contrib/admin/locale'),
)

LANGUAGES = [
     ('ar', _('Arabe')),
]


DECIMAL_SEPARATOR = ','
#THOUSAND_SEPARATOR = '.'
NUMBER_GROUPING = 3
USE_THOUSAND_SEPARATOR=False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
#MEDIA_ROOT = '/home/coaph/coaph/media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
#STATIC_ROOT = '/home/coaph/coaph/static'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
#STATICFILES_FINDERS = (
#    'django.contrib.staticfiles.finders.FileSystemFinder',
#    'django.contrib.staticfiles.finders.AppDirectoriesFinder',    #causes verbose duplicate notifications in django 1.9
#)
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR , "static"),
#]
#ADMIN INTERFACE
X_FRAME_OPTIONS='SAMEORIGIN'

#JET APP settings
#X_FRAME_OPTIONS= 'SAMEORIGIN'

GRAPPELLI_ADMIN_TITLE =_('Administration AGR PSH')

#TABBED_ADMIN_USE_JQUERY_UI = True

CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
]