# Generated by Django 3.1 on 2021-05-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم البطاقة الوطنية')),
                ('acte', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم عقد الازدياد')),
                ('cin_exp_mois', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'ماي'), (6, 'يونيو'), (7, 'يوليوز'), (8, 'غشت'), (9, 'شتنبر'), (10, 'أكتوبر'), (11, 'نونبر'), (12, 'دجنبر')], null=True, verbose_name='شهر انتهاء صلاحية البطاقة')),
                ('cin_exp_annee', models.PositiveSmallIntegerField(blank=True, choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035)], null=True, verbose_name='سنة انتهاء صلاحية البطاقة')),
                ('nom_ar', models.CharField(max_length=30, verbose_name='النسب بالعربية')),
                ('prenom_ar', models.CharField(max_length=30, verbose_name='الاسم بالعربية')),
                ('nom_fr', models.CharField(blank=True, max_length=30, verbose_name='النسب بالفرنسية')),
                ('prenom_fr', models.CharField(blank=True, max_length=30, verbose_name='الاسم بالفرنسية')),
                ('sexe', models.PositiveSmallIntegerField(choices=[(1, 'ذكر'), (2, 'أنثى')], verbose_name='الجنس')),
                ('date_naissance', models.DateField(verbose_name='تاريخ الازدياد')),
                ('age', models.IntegerField(verbose_name='السن')),
                ('lieu_naissance', models.CharField(blank=True, max_length=30, verbose_name='مكان الازدياد')),
                ('nom_tuteur_ar', models.CharField(blank=True, max_length=30, verbose_name='اسم ولي الأمر')),
                ('cin_tuteur', models.CharField(blank=True, max_length=15, verbose_name='رقم بطاقة ولي الأمر')),
                ('adresse', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد إلكتروني')),
                ('telephone', models.CharField(blank=True, max_length=320, verbose_name='الهاتف')),
                ('situation_fam', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'غير محددة'), (2, 'طفل(ة)'), (3, 'عزب(ة)'), (4, 'متزوج(ة)'), (5, 'مطلق(ة)'), (6, 'أرمل(ة)')], default=1, null=True, verbose_name='الحالة العائلية')),
                ('couverture_soc', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'غير محددة'), (2, 'بدون'), (3, 'راميد'), (4, 'الصندوق الوطني للضمان الاجتماعي'), (5, 'الصندوق الوطني لمنظمات الاحتياط الاجتماعي'), (6, 'الصندوق المغربي للتقاعد'), (7, 'الصندوق المهني المغربي للتقاعد'), (8, 'التأمين')], default=1, null=True, verbose_name='التغطية الاجتماعية')),
                ('ramed', models.CharField(blank=True, max_length=20, verbose_name='رقم الراميد')),
                ('ramed_exp_mois', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'ماي'), (6, 'يونيو'), (7, 'يوليوز'), (8, 'غشت'), (9, 'شتنبر'), (10, 'أكتوبر'), (11, 'نونبر'), (12, 'دجنبر')], null=True, verbose_name='شهر انتهاء صلاحية الراميد')),
                ('ramed_exp_annee', models.PositiveSmallIntegerField(blank=True, choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035)], null=True, verbose_name='سنة انتهاء صلاحية الراميد')),
                ('profession', models.CharField(blank=True, max_length=20, verbose_name='المهنة')),
                ('scolarite', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'غير محددة'), (2, 'بدون'), (3, 'ابتدائي'), (4, 'اعدادي'), (5, 'ثانوي'), (6, 'بكالوريا'), (7, 'تقني'), (8, 'جامعي')], default=1, verbose_name='المستوى الدراسي')),
            ],
            options={
                'verbose_name': 'المستفيد',
                'verbose_name_plural': 'المستفيدون',
            },
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_h', models.PositiveSmallIntegerField(choices=[(1, 'حركية'), (2, 'ذهنية'), (3, 'بصرية'), (4, 'سمعية'), (5, 'صوتية')], verbose_name='نوع الإعاقة')),
                ('degre', models.PositiveSmallIntegerField(choices=[(0, 'غير محددة'), (1, 'خفيفة'), (2, 'متوسطة'), (3, 'عميقة')], default=0, verbose_name='درجة الإعاقة')),
                ('duree', models.PositiveSmallIntegerField(choices=[(0, 'غير محددة'), (1, 'دائمة'), (2, 'غير دائمة'), (3, 'متطورة')], default=0, verbose_name='مدة الإعاقة')),
                ('assistance', models.PositiveSmallIntegerField(choices=[(1, 'نعم'), (2, 'لا')], default=2, verbose_name='الحاجة الى مرافق')),
                ('description', models.CharField(blank=True, max_length=30, verbose_name='التوصيف')),
                ('date_h', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('cause_h', models.CharField(blank=True, max_length=30, verbose_name='السبب')),
                ('appareille', models.BooleanField(blank=True, null=True, verbose_name='استعمال معين أو جهاز')),
                ('type_appareil', models.CharField(blank=True, max_length=20, verbose_name='نوع المعين أو الجهاز')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handicaps', to='beneficiaires.beneficiaire', verbose_name='المستفيد')),
            ],
            options={
                'verbose_name': 'الإعاقة',
                'verbose_name_plural': 'الإعاقات',
            },
        ),
    ]
