# Generated by Django 3.1 on 2021-05-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centres', '0001_initial'),
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='adresse_commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires', to='centres.commune', verbose_name='الجماعة'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='adresse_province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires', to='centres.province', verbose_name='العمالة أو الإقليم'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='adresse_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires', to='centres.region', verbose_name='الجهة'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires', to='centres.centre', verbose_name='المركز'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiaire',
            unique_together={('cin', 'acte', 'date_naissance')},
        ),
    ]
