# Generated by Django 3.1 on 2021-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0002_auto_20210509_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='acte',
            field=models.CharField(blank=True, help_text="<i class='fas fa-time-circle'></i>", max_length=20, null=True, verbose_name='رقم عقد الازدياد'),
        ),
    ]
