# Generated by Django 3.1 on 2021-05-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_auto_20210526_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='acte',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم عقد الازدياد'),
        ),
    ]
