# Generated by Django 3.1 on 2021-06-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0004_auto_20210526_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='cin_mere',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم بطاقة الأم'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=30, verbose_name='اسم الأم'),
        ),
        migrations.AlterField(
            model_name='handicap',
            name='type_appareil',
            field=models.CharField(blank=True, max_length=200, verbose_name='نوع المعين أو الجهاز'),
        ),
    ]
