# Generated by Django 3.2.3 on 2022-07-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0007_beneficiaire_situation_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='attestation',
            field=models.CharField(blank=True, max_length=300, verbose_name='Code Vérification Attestation'),
        ),
    ]
