# Generated by Django 3.2.3 on 2022-07-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0008_beneficiaire_attestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='attestation',
            field=models.CharField(blank=True, max_length=300, verbose_name='رمز التحقق من شهادة الإعاقة'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='situation_prof',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'باحث عن عمل'), (2, 'مزاول لنشاط إقتصادي'), (3, 'فترة تكوين'), (4, 'آخر')], default=1, verbose_name='الوضعية المهنية'),
        ),
    ]
