# Generated by Django 3.1 on 2021-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executeurprojet',
            options={'verbose_name': 'حامل المشروع', 'verbose_name_plural': 'حامل المشروع'},
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_certificat',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True, verbose_name='الشهادة الطبية'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_cin',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True, verbose_name='نسخة من البطاقة الوطنية'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_conv_accom',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True, verbose_name='اتفاقية المواكبة'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_conv_finan',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True, verbose_name='اتفاقية التمويل'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_devis',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True, verbose_name='عرض الأثمان التقديري'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_engagement',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True, verbose_name='التزام بتوفير المحل'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_local',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True, verbose_name='مقر انجاز المشروع'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_ramed',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True, verbose_name='نسخة من الراميد'),
        ),
    ]
