# Generated by Django 3.2.3 on 2022-07-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_auto_20220728_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='nature',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Individuel'), (2, 'Collectif')], default=1, null=True, verbose_name='Nature projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='forme_juridique',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'المقاول الذاتي'), (2, 'RC/Personne Physique'), (3, 'شركة'), (4, 'تعاونية'), (5, 'آخر')], null=True, verbose_name='الصيغة القانونية'),
        ),
    ]
