# Generated by Django 3.2.3 on 2022-07-29 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_auto_20220729_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('date_ouverture', models.DateTimeField(verbose_name='Date Ouverture Session')),
                ('date_fermeture', models.DateTimeField(verbose_name='Date Fermeture Session')),
                ('ouverte', models.BooleanField(verbose_name='Session Ouverte')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='projets.session'),
        ),
    ]
