# Generated by Django 3.2.3 on 2022-07-31 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_auto_20220729_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'رأي', 'verbose_name_plural': 'رأي'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'الدورة', 'verbose_name_plural': 'الدورات'},
        ),
        migrations.AlterField(
            model_name='avis',
            name='commission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'اللجنة الإقليمية'), (2, 'اللجنة الجهوية'), (3, 'اللجنة المركزية')], verbose_name='اللجنة'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='forme_juridique',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'المقاول الذاتي'), (2, 'السجل التجاري / شخص ذاتي'), (3, 'شركة'), (4, 'تعاونية'), (5, 'آخر')], null=True, verbose_name='الصيغة القانونية'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nature',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'فردي'), (2, 'جماعي')], default=1, null=True, verbose_name='طبيعة المشروع'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_certificat',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, verbose_name='الشهادة الطبية'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_cin',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, verbose_name='نسخة من البطاقة الوطنية'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_conv_accom',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, verbose_name='اتفاقية المواكبة'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_conv_finan',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, verbose_name='اتفاقية التمويل'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_devis',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, verbose_name='عرض الأثمان التقديري'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_engagement',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, verbose_name='التزام بتوفير المحل'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_local',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, verbose_name='مقر انجاز المشروع'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='piece_ramed',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, verbose_name='نسخة من الراميد'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='projets.session', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_fermeture',
            field=models.DateTimeField(verbose_name='تاريخ انتهاء الدورة'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_ouverture',
            field=models.DateTimeField(verbose_name='تاريخ افتتاح الدورة'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ouverte',
            field=models.BooleanField(verbose_name='الدورة مفتوحة'),
        ),
        migrations.AlterField(
            model_name='session',
            name='titre',
            field=models.CharField(max_length=500, verbose_name='رمز الدورة'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='date_visite',
            field=models.DateTimeField(verbose_name='تاريخ الزيارة'),
        ),
    ]
