# Generated by Django 3.2.3 on 2022-08-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projets', '0007_auto_20220731_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_profil', models.PositiveSmallIntegerField(default=0, verbose_name='Note Profil entrepreneurial')),
                ('note_viabilite', models.PositiveSmallIntegerField(default=0, verbose_name='Note Viabilité du projet')),
                ('note_finance', models.PositiveSmallIntegerField(default=0, verbose_name='Note Aspects financiers')),
                ('note_totale', models.PositiveSmallIntegerField(default=0, verbose_name='Note Totale')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projets.projet', verbose_name='المشروع')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
