# Generated by Django 3.2.3 on 2022-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0008_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='commission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'اللجنة الإقليمية'), (2, 'اللجنة الجهوية'), (3, 'اللجنة المركزية')], default=1, verbose_name='اللجنة'),
        ),
    ]
