# Generated by Django 3.2.3 on 2022-08-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_note_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiviprojet',
            name='avancement',
            field=models.PositiveSmallIntegerField(default=0, help_text='%', verbose_name='Avancement étape'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='secteur',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'الخدمات'), (2, 'التجارة'), (3, 'الصناعة'), (4, 'Agriculture'), (5, 'الصناعة التقليدية'), (6, 'آخر')], null=True, verbose_name='القطاع'),
        ),
    ]
